name: Close stale issues and PRs

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close stale issues/pull requests
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-message: 'This issue has been marked as stale because it has been open for 90 days with no activity. This thread will be automatically closed in 30 days if no further activity occurs.'
          stale-pr-message: 'This pull request has been marked as stale because it has been open for 90 days with no activity. This thread will be automatically closed in 30 days if no further activity occurs.'
          exempt-issue-labels: 'feature request,in progress,dependencies'
          days-before-stale: 90
          days-before-close: 30
