name: Close stale issues and PRs

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues/pull requests
        uses: actions/stale@v8.0.0
        with:
          stale-issue-message: 'This issue has been marked as stale because it has been open for 90 days with no activity. This thread will be automatically closed in 30 days if no further activity occurs.'
          stale-pr-message: 'This pull request has been marked as stale because it has been open for 90 days with no activity. This thread will be automatically closed in 30 days if no further activity occurs.'
          exempt-issue-labels: 'feature request,in progress'
          days-before-stale: 90
          days-before-close: 30
